---

- hosts: website
  vars:
    repo_url: 'https://github.com/rzhouac/website-template.git'
    repo_dest: "{{ ansible_env.HOME }}/website"
    template_location: "{{ repo_dest }}/index.html"
  roles:
    - git
    - nginx